version: '3.9'

services:
  backend: 
    build: ./backend
    image: lumaghg/dualis-bot-backend
    ports: 
      - 4000:4000
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - AES_SECRET=${AES_SECRET}
      - CRAWLER_URL=${CRAWLER_URL}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - TELEGRAM_BOT=${TELEGRAM_BOT}
      - WEBSITE=${WEBSITE}
    depends_on:
      - dualis-crawler
    
  dualis-crawler:
    build: ./dualis-crawler
    image: lumaghg/dualis-crawler

  frontend:
    build: ./frontend
    image: lumaghg/dualis-frontend
    ports: 
      - 80:80
    depends_on:
    - dualis-crawler
    - backend
