version: '3'

services:
  postgressql:
    image: 'postgres:latest'
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: default_database # The PostgreSQL default database (automatically created at first launch)
    volumes:
      - "postgres-data:/var/lib/postgresql/data/"
volumes:
  postgres-data:
