version: '3.9'

services:
  backend: 
    image: lumaghg/dualis-backend
    labels:
      - "traefik.http.routers.backend.rule=Host(`api.dualis-bot.robin-reyer.de`)"
    #ports: 
    #  - 4000:4000
    environment:
      - BACKEND_PORT
      - JWT_SECRET
      - AES_SECRET
      - CRAWLER_URL
      - DATABASE_PASSWORD
      - TELEGRAM_BOT
      - WEBSITE
    restart: always
    depends_on: 
      - crawler
      - reverse-proxy
    
  crawler:
    image: lumaghg/dualis-crawler
    labels:
      - traefik.enable=false
    depends_on:
    - reverse-proxy
    restart: always

  frontend:
    image: lumaghg/dualis-frontend
    labels:
      - "traefik.http.routers.frontend.rule=Host(`dualis-bot.robin-reyer.de`)"
    #ports: 
    #  - 4001:80
    depends_on:
    - crawler
    - backend
    - reverse-proxy
    restart: always
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.6
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=false --providers.docker
    restart: always
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      # - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock 
    
    
