name: Copy Hosting to Server

on:
  push:
    branches: [ main ]
    paths:
      - "hosting/**"
  pull_request:
    branches: [ main ]
    paths:
      - "hosting/**"

jobs:
  deploy:
    name: Build and Push Frontend
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@master

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "/hosting/docker-compose-prod.yml"
          target: "/home/administrator"