name: Copy Hosting to Server

on:
  push:
    branches: [ main ]
    paths:
      - "hosting/**"
  pull_request:
    branches: [ main ]
    paths:
      - "hosting/**"

jobs:
  deploy:
    name: Copy files to Server
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@master

      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "./hosting/docker-compose-prod.yml"
          target: "~/"
      
      - name: Apply docker-compose changes
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PASSWORD: ${{ secrets.SSH_PASSWORD }}
          PORT: ${{ secrets.SSH_PORT }}
          script: |
            # restart containers, if neccessary
            docker-compose -f ./hosting/docker-compose-prod.yml up -d