name: Dualis-Crawler CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - "dualis-crawler/**"
  pull_request:
    branches: [ main ]
    paths:
      - "dualis-crawler/**"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16


    - name: Build
      run: go build -v ./main.go
      working-directory: ./dualis-crawler

    - name: Test
      run: go test -v -covermode=atomic ./...
      working-directory: ./dualis-crawler