name: Frontend CD

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
  pull_request:
    branches: [ main ]
    paths:
      - "frontend/**"

jobs:
  build_deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Build Frontend Docker Image
        run: docker build -t lumaghg/dualis-frontend ./frontend

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image to Dockerhub
        run: docker push lumaghg/dualis-frontend

      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PASSWORD: ${{ secrets.SSH_PASSWORD }}
          PORT: ${{ secrets.SSH_PORT }}
          script: |
            # Login to docker
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            # Pull the new image from Dockerhub
            docker pull lumaghg/dualis-frontend:latest
            # Replace the container
            docker-compose up -d frontend
