name: Frontend CD

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
  pull_request:
    branches: [ main ]
    paths:
      - "frontend/**"

jobs:
  build_deploy:
    name: Build and Deploy Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend
    env:
      BUILD_VER: 1.0.${{env.GITHUB_RUN_NUMBER}}
      IMAGE: lumaghg/dualis-frontend

    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push container image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.IMAGE }}:latest
            ${{ env.IMAGE }}:${{ env.BUILD_VER}}


      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PASSWORD: ${{ secrets.SSH_PASSWORD }}
          PORT: ${{ secrets.SSH_PORT }}
          script: |
            # Login to docker
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            # Pull the new image from Dockerhub
            docker pull lumaghg/dualis-frontend:latest
            # Replace the container
            docker-compose up -d frontend
