name: Frontend CD

on:
  push:
    branches: [ main ]
    paths:
      - "frontend/**"
  pull_request:
    branches: [ main ]
    paths:
      - "frontend/**"

jobs:
  build:
    name: Build and Push Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Build Frontend Docker Image
        run: docker build -t lumaghg/dualis-frontend ./frontend

      - name: Docker Login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Image to Dockerhub
        run: docker push lumaghg/dualis-frontend

  deploy: 
      name: Deploy Frontend
      needs: build
      runs-on: ubuntu-latest

      steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: ${{ secrets.SSH_HOST }}
          USERNAME: ${{ secrets.SSH_USERNAME }}
          PASSWORD: ${{ secrets.SSH_PASSWORD }}
          PORT: ${{ secrets.SSH_PORT }}
          script: |
            # Login to docker
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            # Pull the new image from Dockerhub
            docker pull lumaghg/dualis-frontend:latest
            # Replace the container
            EMAIL=${{ secrets.EMAIL }}\
            EMAIL_PASS=${{ secrets.EMAIL_PASS }} \
            SMTP_HOST=${{ secrets.SMTP_HOST }} \
            BACKEND_PORT=${{ secrets.BACKEND_PORT }} \
            DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} \
            JWT_SECRET=${{ secrets.JWT_SECRET }} \
            AES_SECRET=${{ secrets.AES_SECRET }} \
            CRAWLER_URL=${{ secrets.CRAWLER_URL }} \
            TELEGRAM_BOT=${{ secrets.TELEGRAM_BOT }} \
            WEBSITE=${{ secrets.WEBSITE }} \
            DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} \
            docker-compose -f ./hosting/docker-compose-prod.yml up -d --no-deps frontend
